### ISSUE TITLE
Tweaks needed for deploy

### ISSUE THREAD

**Issue by aarongustafson** [codetheweb/scrabblescore#1]
We either need you to include a web.config file pointing to `./dist` as the root folder _or_ we need the site to be in the root folder of the repository. Otherwise it won’t deploy correctly.

**Comment by codetheweb** [comment]
Does it look good now @aarongustafson?  (If the format of the web.config file isn't correct, I'm okay with putting the dist/\* files in the root of the repository.  Is it possible to instead deploy with the `gh-pages` branch of this repo?)

**Comment by aarongustafson** [comment]
We can only deploy from master. I’ll add it to the queue and let you know
if it fails.

**Comment by aarongustafson** [comment]
It didn’t fail, but it’s also not working: https://scrabble-score-10kapart2016.azurewebsites.net/

**Comment by codetheweb** [comment]
If I go to https://scrabble-score-10kapart2016.azurewebsites.net/dist/index.html it works fine.  I’ve never used ASP.NET before so I guess I just messed up the config file.

I copied the files to the root of the repository, so it should work now.

If it does deploy successfully, can I then delete them?

**Comment by aarongustafson** [comment]
Ah yes, we need them in the root. I will re-sync.

**Comment by aarongustafson** [comment]
I found a setting that let me set /dist as the root. It’s working now: http://scrabble-score-10kapart2016.azurewebsites.net/

**Comment by codetheweb** [comment]
Yay!  So I can delete the files in root now?

**Comment by aarongustafson** [comment]
Yes
